on: create

name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Packages
        run: yarn install
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v6
        with:
          PACKAGE_MANAGER: yarn
          BUILD_COMMAND: yarn package
      - name: Release NPM
        uses: epeli/npm-release@v1
        with:
          type: stable
          token: ${{ secrets.NPM_TOKEN }}
