name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Packages
        run: yarn install
      - name: Bump new Package Version
        run: npm version --new-version ${{ github.event.release.tag_name }} -no-git-tag-version
      - name: Commit new Package Version
        uses: EndBug/add-and-commit@v5
        with:
          message: 'ci: Bump ${{ github.event.release.tag_name }}'
          add: 'package.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to GitHub Actions Market
        uses: technote-space/release-github-actions@v6
        with:
          PACKAGE_MANAGER: yarn
          BUILD_COMMAND: yarn package
      - name: Setup nodejs for NPM Registry
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Rlease to NPM Registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup nodejs for NPM Registry
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Rlease to GitHub Registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
